version: "3"
services:
  node-app:
    image: ashishbarvaliya/node-api-prod
    build:
      context: .
      args:
        NODE_ENV: production
    env_file:
      - ./.env.prod
    command: npm run prod